### PR TITLE
Add Llama Aave Treasury Tables - Polygon

### PR DESCRIPTION
**Pull request by MSilb7**
Similar to https://github.com/duneanalytics/abstractions/pull/700 but for Polygon

I've checked that:

* [ ] the query produces the intended results
* [ ] the folder name matches the schema name
* [ ] the schema name exists in Dune
* [ ] views are prefixed with `view_`, functions with `fn_`.
* [ ] the filename matches the defined view, table or function and ends with .sql
* [ ] each file has only one view, table or function defined  
* [ ] column names are `lowercase_snake_cased`

### CODE REVIEW

**Comment by MSilb7** [comment]
Similar to #700 I *think* this should all match up now.

**Comment by MSilb7** [comment]
Hi, following up to see if this is good to go?

**Comment by MSilb7** [comment]
Also removed `dune_user_generated` here.

**Comment by MSilb7** [comment]
Hi, bumping this back up again!

**Comment by scottincrypto** [comment]
Hi, any chance these can be pushed through?

**Review by jeff-dude — APPROVED** [review]
@MSilb7 revisited this old one. i pushed quite a few commits and loaded / enabled automation on polygon. hope this is as expected. note that llama_aave_treasury/insert_aave_daily_treasury_fees.sql file inserted 0 rows, query doesn't return results

**Comment by jeff-dude** [comment]
@scottincrypto fyi

**Pull request merged**
