### PR TITLE
Add SingularityNET Foundation tokens for get price feed

### PR DESCRIPTION
**Pull request by singularitydao**
* add AGIX price feed
* add SDAO price feed
* add NTX price feed

### CODE REVIEW

**Comment by TomoHavvk** [comment]
AGIX Token API: https://api.coinpaprika.com/v1/coins/agix-singularitynet
SDAO Token API: https://api.coinpaprika.com/v1/coins/sdao-singularitydao
NTX Token API: https://api.coinpaprika.com/v1/coins/ntx-nunet

I've checked that:

- [ ] the query produces the intended results
- [ ] column names are lowercase_snake_cased

**Comment by singularitydao** [comment]
AGIX Token API: https://api.coinpaprika.com/v1/coins/agix-singularitynet
SDAO Token API: https://api.coinpaprika.com/v1/coins/sdao-singularitydao
NTX Token API: https://api.coinpaprika.com/v1/coins/ntx-nunet

I've checked that:

- [ ] the query produces the intended results
- [ ] column names are lowercase_snake_cased

**Comment by singularitydao** [comment]
@masquot , @k06a please review

**Review by masquot — APPROVED** [review]
Thank you @singularitydao.

**Pull request merged**
