### PR TITLE
index: update Indexed Finance data-tables

### PR DESCRIPTION
**Pull request by laurenceday**
I've checked that:

* [x] the query produces the intended results
* [x] the folder name matches the schema name
* [x] the schema name exists in Dune
* [x] views are prefixed with `view_`, functions with `fn_`.
* [x] the filename matches the defined view, table or function and ends with .sql
* [x] each file has only one view, table or function defined  
* [x] column names are `lowercase_snake_cased`

### CODE REVIEW

**Comment by milkyklim** [comment]
@mewwts tables are in but need help updating price.ini than can merge.

**Comment by laurenceday** [comment]
Hi, just following up on this PR - anything I can do in particular, @milkyklim? Or [going off the last comment] is this in @mewwts' court?

**Comment by 0xBoxer** [comment]
hey @laurenceday , we are not able to change what assets are listed on coinpaprika, please get in touch with them to get your assets listed over there. I have deleted the changes to prices.ini, the rest looks good to me

**Review by 0xBoxer — APPROVED** [review]

**Comment by laurenceday** [comment]
Will do, thanks!

**Comment by mewwts** [comment]
I understood from @milkyklim that these tables have been updated already! Changes to prices.ini seem to have come in from other PRs.

**Pull request merged**
