### PR TITLE
Mirror writers 022422

### PR DESCRIPTION
**Pull request by andrewhong5297**
I've checked that:

* [x] the query produces the intended results
* [x] the folder name matches the schema name
* [x] the schema name exists in Dune
* [x] views are prefixed with `view_`, functions with `fn_`.
* [x] the filename matches the defined view, table or function and ends with .sql
* [x] each file has only one view, table or function defined  
* [x] column names are `lowercase_snake_cased`

These are 30k writer addresses on Mirror with a bunch of summed numerical and metadata columns. Let me know if there's anything I should change - thanks!

### CODE REVIEW

**Comment by masquot** [comment]
Thank you @andrewhong5297. The code looks excellent. The only issue is that there appear to be duplicate entries - this one is from the ethereum file:
```
psql:mirror_writers.sql:33: ERROR:  duplicate key value violates unique constraint "writer_addresses_pkey"
DETAIL:  Key (address)=(\x3b3525f60eeea4a1ef554df5425912c2a532875d) already exists.
```

**Comment by andrewhong5297** [comment]
whoops! should have checked that, my bad 😅  

just committed a fix for it!

**Review by masquot — APPROVED** [review]
Thank you @andrewhong5297. Mirror writers data is now available :rocket:

**Comment by andrewhong5297** [comment]
amazing, thank you!

**Pull request merged**
