### PR TITLE
add dodo liquidity

### PR DESCRIPTION
**Pull request by bizzyvinci**
This is unfinished as I don't understand dododex well. The 3 major issues are 
1. DODO has V1 and V2
2. I don't think all dodo pools are included in `dodo_pools` table
3. I don't know the genesis of DODO (so I started from 2021 Q1)

Also, what's the tabbing standard?

### CODE REVIEW

**Comment by jeff-dude** [comment]
@bizzyvinci apologies for the delay on this PR. i had noticed it was in draft and overlooked it. i can start to take a closer look and help work through a few of your points listed in the description

**Comment by jeff-dude** [comment]
> This is unfinished as I don't understand dododex well. The 3 major issues are
> 
> 1. DODO has V1 and V2
> 2. I don't think all dodo pools are included in `dodo_pools` table
> 3. I don't know the genesis of DODO (so I started from 2021 Q1)
> 
> Also, what's the tabbing standard?

@bizzyvinci 
1. for v1 & v2, we typically look to do two separate files. look at uniswap as an example with three files for three versions
2. can you use the dodo dex trades query as inspiration to find full list of pools? with a quick glance, for v2 specifically, i see a theme for DPP, DSP and DVM. quick search of the dodo tables shows maybe these could be useful:
`select *
from dodo."DPPFactory_evt_NewDPP"
union all
select *
from dodo."DSPFactory_evt_NewDSP"
union all
select *
from dodo."DVMFactory_evt_NewDVM"`
3. for the genesis, you can refer to dex trades insert function as well to either find the tables to query for first events or use the same date in their function calls at the end (i.e. 2020-01-01 used in dex trades). even if there isn't data, it doesn't hurt to run the function call.

**Comment by bizzyvinci** [comment]
Thanks @jeff-dude. I will use the dex as a guide.

**Comment by bizzyvinci** [comment]
It's ready for review @jeff-dude

**Comment by jeff-dude** [comment]
> It's ready for review @jeff-dude

fyi the historical loads are in process now. i will merge the PR once complete.

**Comment by bizzyvinci** [comment]
Thanks. But I noticed you didn't update function calls for v2.

**Comment by jeff-dude** [comment]
> Thanks. But I noticed you didn't update function calls for v2. My bad for not using the right call early on.

i've updated v2 locally while running & will push when it's complete and ready to finalize the merge. good catch though!

**Review by jeff-dude — APPROVED** [review]
@bizzyvinci files should be updated here & the cron jobs have been enabled. feel free to open new PR if anything seems off.

**Comment by bizzyvinci** [comment]
It looks good. Thanks.

**Pull request merged**
