### PR TITLE
added rndr-render to abstractions/prices/ethereum/coinpaprika.yaml

### PR DESCRIPTION
**Pull request by ssolit**
Brief comments on the purpose of your changes:

*For Dune Engine V2*
I've checked that:

* [ ] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [ ] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [ ] if adding a new model, I added a test
* [ ] the filename is unique and ends with .sql
* [ ] each sql file is a select statement and has only one view, table or function defined  
* [ ] column names are `lowercase_snake_cased`

When you are ready for a review, tag duneanalytics/data-experience. We will re-open your forked pull request as an internal pull request. Then your spells will run in dbt and the logs will be avaiable in Github Actions DBT Slim CI. This job will only run the models and tests changed by your PR compared to the production project.

### CODE REVIEW

**Review by jeff-dude — APPROVED** [review]
@ssolit thank you for the addition

**Comment by ssolit** [comment]
Hello,

Do you have any estimate for how long after a merge like this you can start querying the new token on the Dune site?

Thanks

**Comment by jeff-dude** [comment]
> Hello,
> 
> Do you have any estimate for how long after a merge like this you can start querying the new token on the Dune site?
> 
> Thanks

hi @ssolit -- it gets loaded quickly after the merge. please see below as example:
```
select date_trunc('day', minute)
    , avg(price)
from prices.usd
where symbol = 'RNDR'
group by date_trunc('day', minute)
order by 1 desc
limit 10
;
```

**Comment by ssolit** [comment]
Hi Jeff,

Thank you for replying. This seemed to work when I ran it on the Ethereum dataset, but not when I'm trying to work on Polygon data (which I am currently trying to do). Below is the query I'm running:

`WITH
rndr_prc AS (
    select date_trunc('hour', minute) as hour, avg(price)
    from prices.usd
    where symbol = 'RNDR'
    group by date_trunc('hour', minute)
    order by 1 desc
    limit 10
),
payments as (
    select date_trunc('hour',t.evt_block_time) as h, sum(t.value/1000000000000000000) as n
    from polygon."traces" e inner join erc20."ERC20_evt_Transfer" t on e.tx_hash = t.evt_tx_hash
    where e."from" = '\xD6C17bCC364C3a5C0F3C4eadA5Ce8e5213B62C3B'
    group by 1
)

select * from rndr_prc`

This results in "No results from query."

Is there a different file you have to edit to make the price show up for polygon data? My ultimate goal is to multiply the price by the Polygon payments to get the payment amount in USD. 

Thank you for the help!

**Comment by jeff-dude** [comment]
> Hi Jeff,
> 
> Thank you for replying. This seemed to work when I ran it on the Ethereum dataset, but not when I'm trying to work on Polygon data (which I am currently trying to do). Below is the query I'm running:
> 
> ```
> WITH
> rndr_prc AS (
>     select date_trunc('hour', minute) as hour, avg(price)
>     from prices.usd
>     where symbol = 'RNDR'
>     group by date_trunc('hour', minute)
>     order by 1 desc
>     limit 10
> ),
> payments as (
>     select date_trunc('hour',t.evt_block_time) as h, sum(t.value/1000000000000000000) as n
>     from polygon."traces" e inner join erc20."ERC20_evt_Transfer" t on e.tx_hash = t.evt_tx_hash
>     where e."from" = '\xD6C17bCC364C3a5C0F3C4eadA5Ce8e5213B62C3B'
>     group by 1
> )
> 
> select * from rndr_prc
> ```
> 
> This results in "No results from query."
> 
> Is there a different file you have to edit to make the price show up for polygon data? My ultimate goal is to multiply the price by the Polygon payments to get the payment amount in USD.
> 
> Thank you for the help!

ah, i see what you're trying to do. yes, there are different files for different chains:
https://github.com/duneanalytics/abstractions/tree/master/prices

you can find polygon directory there, along with README on how to add (notice polygon is coingecko vs. coinpaprika from this PR)

**Pull request merged**
