### PR TITLE
Add and expose optimism airdrop address list

### PR DESCRIPTION
**Pull request by soispoke**
Brief comments on the purpose of your changes:

*For Dune Engine V2*
I've checked that:

* [ ] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [ ] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [ ] if adding a new model, I added a test
* [ ] the filename is unique and ends with .sql
* [ ] each sql file is a select statement and has only one view, table or function defined  
* [ ] column names are `lowercase_snake_cased`

When you are ready for a review, tag duneanalytics/data-experience. We will re-open your forked pull request as an internal pull request. Then your spells will run in dbt and the logs will be avaiable in Github Actions DBT Slim CI. This job will only run the models and tests changed by your PR compared to the production project.

### CODE REVIEW

**Comment by soispoke** [comment]
@MSilb7 I heard you wanted to expose this address list as an abstraction, let me know if this works for you ?

**Comment by dot2dotseurat** [comment]
> @MSilb7 I heard you wanted to expose this address list as an abstraction, let me know if this works for you ?

@soispoke this address file fails when we try to run it as a model likely due to the size.

**Comment by dot2dotseurat** [comment]
> > @MSilb7 I heard you wanted to expose this address list as an abstraction, let me know if this works for you ?
> 
> Hi, yeah. I see the schema placement was modified which is fine (whatever works best).
> 
> Also (if it matters) noticed some of the tags say `mslib7` instead of `msilb7`

I can update the tags when I deploy it. We can't merge this in because the automation tool dbt cloud can't handle the file size. But what I can do is deploy it manually from the CLI. We will move to a new automation tool next quarter which will resolve the file size issue. Not sure why dbt cloud has this issue but I'm going to let them know.

**Comment by dot2dotseurat** [comment]
@MSilb7 `airdrop_optimism.addresses` is now queryable on dune.com. I will make it visible in the data explorer soon.

**Comment by MSilb7** [comment]
> @MSilb7 `airdrop_optimism.addresses` is now queryable on dune.com. I will make it visible in the data explorer soon (done).

Hi awesome!

Should this be labeled differently? (i.e. specific to Optimism). Also `airdrop_optimism.addresses_airdrop1` or something like that would be better, since there will be multiple airdrops.

image

**Comment by dot2dotseurat** [comment]
> > @MSilb7 `airdrop_optimism.addresses` is now queryable on dune.com. I will make it visible in the data explorer soon (done).
> 
> Hi awesome!
> 
> Should this be labeled differently? (i.e. specific to Optimism). Also `airdrop_optimism.addresses_airdrop1` or something like that would be better, since there will be multiple airdrops.
> 
> image

How about `optimism.airdrop_addresses_1` ? Then we aren't saying airdrop twice.

**Comment by MSilb7** [comment]
> > > @MSilb7 `airdrop_optimism.addresses` is now queryable on dune.com. I will make it visible in the data explorer soon (done).
> > 
> > 
> > Hi awesome!
> > Should this be labeled differently? (i.e. specific to Optimism). Also `airdrop_optimism.addresses_airdrop1` or something like that would be better, since there will be multiple airdrops.
> > image
> 
> How about `optimism.airdrop_addresses_1` ? Then we aren't saying airdrop twice.

That would work.

Or other alternative, if we imagine a namespace for all address lists, it could be: `optimism_addresses.airdrop_1`

**Comment by dot2dotseurat** [comment]
> > > > @MSilb7 `airdrop_optimism.addresses` is now queryable on dune.com. I will make it visible in the data explorer soon (done).
> > > 
> > > 
> > > Hi awesome!
> > > Should this be labeled differently? (i.e. specific to Optimism). Also `airdrop_optimism.addresses_airdrop1` or something like that would be better, since there will be multiple airdrops.
> > > image
> > 
> > 
> > How about `optimism.airdrop_addresses_1` ? Then we aren't saying airdrop twice.
> 
> That would work.
> 
> Or other alternative, if we imagine a namespace for all address lists, it could be: `optimism_addresses.airdrop_1`

@MSilb7 up to you! I think either make sense. Just let me know which you prefer and I can redeploy under that namespace.

**Comment by MSilb7** [comment]
> > > > > @MSilb7 `airdrop_optimism.addresses` is now queryable on dune.com. I will make it visible in the data explorer soon (done).
> > > > 
> > > > 
> > > > Hi awesome!
> > > > Should this be labeled differently? (i.e. specific to Optimism). Also `airdrop_optimism.addresses_airdrop1` or something like that would be better, since there will be multiple airdrops.
> > > > image
> > > 
> > > 
> > > How about `optimism.airdrop_addresses_1` ? Then we aren't saying airdrop twice.
> > 
> > 
> > That would work.
> > Or other alternative, if we imagine a namespace for all address lists, it could be: `optimism_addresses.airdrop_1`
> 
> @MSilb7 up to you! I think either make sense. Just let me know which you prefer and I can redeploy under that namespace.

Hi, so sorry for not getting back.
I think `optimism_addresses.op_airdrop_1` could work (clarifying it's the OP token vs any other future airdrops on Optimism from other projects). While I'm still picking up the naming conventions, my goal would be:

Abstraction schema name shows as `address_lists` (or any other convention you all prefer), OP logo is shown rather than ETH, table is named `op_airdrop_1`

**Pull request closed without merging**
