### PR TITLE
Add pre-2022 1inch trades to zerion.trades

### PR DESCRIPTION
**Pull request by hildobby**
Brief comments on the purpose of your changes:
Adding missing 1inch tradres to zerion.trades

*For Dune Engine V2*
I've checked that:

* [ ] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [ ] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [ ] if adding a new model, I added a test
* [ ] the filename is unique and ends with .sql
* [ ] each sql file is a select statement and has only one view, table or function defined  
* [ ] column names are `lowercase_snake_cased`

When you are ready for a review, tag duneanalytics/data-experience. We will re-open your forked pull request as an internal pull request. Then your spells will run in dbt and the logs will be avaiable in Github Actions DBT Slim CI. This job will only run the models and tests changed by your PR compared to the production project.

### CODE REVIEW

**Comment by hildobby** [comment]
> @hildobby the file added here is empty. i assume you just want me to look at the existing script in 'master' and backfill for data prior to 2022? then would you want me to just close this PR since there isn't anything to merge?

Oh my bad, re-pushed the file and it's not empty now, haha sorry

**Comment by jeff-dude** [comment]
> > @hildobby the file added here is empty. i assume you just want me to look at the existing script in 'master' and backfill for data prior to 2022? then would you want me to just close this PR since there isn't anything to merge?
> 
> Oh my bad, re-pushed the file and it's not empty now, haha sorry

glad i asked 😅 i'll look to get this loaded now

**Comment by jeff-dude** [comment]
@hildobby please take a look at my latest commit here. are you okay with proposed changes?

another view:
https://dune.com/queries/1062004?start_ts_d83555=2021-01-01+00%3A00%3A00

**Comment by hildobby** [comment]
> @hildobby please take a look at my latest commit here. are you okay with proposed changes?
> 
> another view: https://dune.com/queries/1062004?start_ts_d83555=2021-01-01+00%3A00%3A00

Yes that's perfect, thanks!!

**Review by jeff-dude — APPROVED** [review]
@hildobby okay, 2020 & 2021 were backfilled 👍

**Pull request merged**
