### PR TITLE
Add PLINK-USD and refactor dYdX perps

### PR DESCRIPTION
**Pull request by ivigamberdiev**
I've checked that:

* [ ] the query produces the intended results
* [ ] the folder name matches the schema name
* [ ] the schema name exists in Dune
* [ ] views are prefixed with `view_`, functions with `fn_`.
* [ ] the filename matches the defined view, table or function and ends with .sql
* [ ] each file has only one view, table or function defined  
* [ ] column names are `lowercase_snake_cased`

### CODE REVIEW

**Comment by mewwts** [comment]
@hagaetc can you take a look at this?

**Comment by hagaetc** [comment]
Looks good to me! Thanks @ivigamberdiev 👍

**Review by hagaetc — APPROVED** [review]

**Comment by mewwts** [comment]
merged here https://github.com/duneanalytics/abstractions/commit/ef31945c4bd531a3f82f5665469057dc3f9e429e

**Comment by mewwts** [comment]
@hagaetc @ivigamberdiev https://discord.com/channels/757637422384283659/757893948428517376/799702159020130314

**Comment by ivigamberdiev** [comment]
Fixed in #213

**Pull request closed without merging**
