### PR TITLE
Add Unifi to dex.trades on Ethereum

### PR DESCRIPTION
**Pull request by lolboysg**
Added Unifi DEX to dex.trades table on Ethereum as requested in #603.
Results of the Unifi query can be checked at the dune_user_generated.unifi table.

I've checked that:

* [x] the query produces the intended results
* [x] the folder name matches the schema name
* [x] the schema name exists in Dune
* [x] views are prefixed with `view_`, functions with `fn_`.
* [x] the filename matches the defined view, table or function and ends with .sql
* [x] each file has only one view, table or function defined  
* [x] column names are `lowercase_snake_cased`

### CODE REVIEW

**Comment by dsalv** [comment]
Thank you for your contribution @lolboysg

I executed the query and loaded the results in a test query here: https://dune.xyz/queries/303778

I have compared the volume from the query results and the metrics on the following page https://unifi.report/ - seems like the results do not match? Please, make sure that all the swap contracts are covered by your query. It is possible that some contracts are not decoded on Dune yet.

**Comment by lolboysg** [comment]
@dsalv true I've forgot to add v1 contracts doing it rn

**Comment by lolboysg** [comment]
@dsalv I don't really get it how the result doesn't match because so far it does (don't forget it's only ethereum)

**Comment by lolboysg** [comment]
In fact the only thing missing are the V1 contracts but they don't have any volumes for a few months

**Comment by dsalv** [comment]
Yes, thanks for clarifying, the volume on ethereum is indeed ~720 on that day, since the most of the volume comes from other networks. Please, make sure that your submission follow 1inch pattern where token_a corresponds to token bought.

**Comment by dsalv** [comment]
The interface looks similar to Uniswap V2. Please, make sure that the following check `CASE WHEN "amount0In" = 0` covers all edge cases. You can see in this [PR](https://github.com/duneanalytics/abstractions/pull/687) that this check doesn't work if  `amount0In` was used in a different context. Additional check might be required.

**Comment by lolboysg** [comment]
You're true it's a fork from Uniswap v2. However I don't think there might me additional checks required so far as I've searched in the router contract code. Anyway thanks a lot for the feedback

**Comment by dsalv** [comment]
Thank you @lolboysg

Checks:


- [ ] token_a is the token bought

- [ ] basic check vs https://unifi.report/ 

- [ ] USD amounts also for ETH -> not applicable here

Looks fine to me.

**Comment by lolboysg** [comment]
@masquot could you review this ?

**Comment by masquot** [comment]
Sorry for the delay @lolboysg. Approved and merged :rocket:

**Review by masquot — APPROVED** [review]

**Pull request merged**
