### PR TITLE
import new token price solana

### PR DESCRIPTION
**Pull request by alkinemk**
New price for DUST

### CODE REVIEW

**Comment by jeff-dude** [comment]
thank you @alkinemk for the PR.

@aalan3 can you confirm for solana prices?

**Comment by aalan3** [comment]
@alkinemk I'll add DUST when https://github.com/duneanalytics/abstractions/pull/1379 is merged, this file will no longer be in use after that.

**Comment by jeff-dude** [comment]
closing due to comment above

**Comment by aalan3** [comment]
New PR here: https://github.com/duneanalytics/abstractions/pull/1381

Will be deployed tomorrow most likely.

**Pull request closed without merging**
