### PR TITLE
Tokemak

### PR DESCRIPTION
**Pull request by mfuribondo**
Brief comments on the purpose of your changes:

*For Dune Engine V2*
I've checked that:

* [x] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [x] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [x] if adding a new model, I added a test
* [x] the filename is unique and ends with .sql
* [x] each sql file is a select statement and has only one view, table or function defined  
* [x] column names are `lowercase_snake_cased`

When you are ready for a review, tag duneanalytics/data-experience. We will re-open your forked pull request as an internal pull request. Then your spells will run in dbt and the logs will be avaiable in Github Actions DBT Slim CI. This job will only run the models and tests changed by your PR compared to the production project.

### CODE REVIEW

**Comment by mfuribondo** [comment]
This PR should only be for adding in the latest commit 
009d9db 
as the previous ones were already merged into master

**Comment by jeff-dude** [comment]
as an FYI, since built as materialized views, rebuilding from lookup tokens view causes downstream drops. i'll rebuild any listed here which are in the 'tokemak' schema, but dune user generated ones will need rebuilt.

view_tokemak_lookup_tokens.sql:2: NOTICE:  drop cascades to 30 other objects
DETAIL:  drop cascades to materialized view tokemak.view_tokemak_curve_convex_pool_total_supply
drop cascades to materialized view tokemak.view_tokemak_convex_pool_stats_daily
drop cascades to materialized view tokemak.view_tokemak_curve_pool_stats_daily
drop cascades to materialized view tokemak.view_tokemak_reactor_balances_daily
drop cascades to materialized view tokemak.view_tokemak_sushiswap_pool_stats_daily
drop cascades to materialized view tokemak.view_tokemak_uniswap_pool_stats_daily
drop cascades to materialized view tokemak.view_tokemak_wallet_balances_daily
drop cascades to view dune_user_generated.tokemak_deployed_asset_balances_base
drop cascades to view dune_user_generated.tokemak_prices_usd_eth_daily
drop cascades to view dune_user_generated.tokemak_outstanding_liabilities_daily
drop cascades to view dune_user_generated.tokemak_wallet_balances_nonlp_daily
drop cascades to view dune_user_generated.tokemak_wallet_balances
drop cascades to materialized view tokemak.view_tokemak_prices_usd_eth_daily
drop cascades to materialized view tokemak.view_tokemak_outstanding_liabilities_daily
drop cascades to view dune_user_generated.tokemak_curve_convex_pool_total_supply
drop cascades to view dune_user_generated.tokemak_convex_pool_stats_daily
drop cascades to view dune_user_generated.tokemak_deployed_asset_balances_daily
drop cascades to view dune_user_generated.tokemak_all_deployable_assets_by_asset_daily
drop cascades to view dune_user_generated.tokemak_pcas_daily
drop cascades to view dune_user_generated.tokemak_wallet_balances_daily
drop cascades to view dune_user_generated.tokemak_uniswap_pool_stats_daily
drop cascades to materialized view tokemak.view_tokemak_deployed_asset_balances_daily
drop cascades to materialized view tokemak.view_tokemak_all_deployable_assets_by_asset_daily
drop cascades to materialized view tokemak.view_tokemak_pcas_daily
drop cascades to view dune_user_generated.tokemak_prices_usd_latest
drop cascades to view dune_user_generated.tokemak_reactor_balances
drop cascades to view dune_user_generated.tokemak_wallet_balances_nonlp
drop cascades to view dune_user_generated.tokemak_sushiswap_pool_stats_daily
drop cascades to view dune_user_generated.tokemak_curve_pool_stats_daily
drop cascades to view dune_user_generated.tokemak_reactor_balances_daily

**Comment by mfuribondo** [comment]
understood, thanks!

**Review by jeff-dude — APPROVED** [review]
@mfuribondo thank you for the changes, should be all applied 👍

**Pull request merged**
