### PR TITLE
[Easy] Add 15 missing tokens

### PR DESCRIPTION
**Pull request by gentrexha**
Usual token update taken from missing tokens query:

https://dune.com/queries/236085

(Since Ben is off)

### CODE REVIEW

**Review by josojo — APPROVED** [review]
thanks

**Comment by bh2smith** [comment]
For the V2 update, we use a different query:

https://dune.com/queries/984709

There are actually 19 missing tokens there.

**Review by bh2smith — APPROVED** [review]
Looks good!

**Review by jeff-dude — APPROVED** [review]
thank you @gentrexha

**Comment by bh2smith** [comment]
Hey, I am not sure if the V2 token list was updated here but the missing tokens in this query is still quite large:

https://dune.com/queries/984709

**Comment by jeff-dude** [comment]
> Hey, I am not sure if the V2 token list was updated here but the missing tokens in this query is still quite large:
> 
> https://dune.com/queries/984709

we do manual deploys to v2 right now & we haven't deployed since this was merged. we will look to do one soon.

**Pull request merged**
