### PR TITLE
opensea-solana transfers added

### PR DESCRIPTION
**Pull request by sohwak**
Brief comments on the purpose of your changes:

I think I will make it to replace the current `opensea_solana.events`, but I am going to make it as a temporary version, not a fixed version so I just name this as `opensea_solana.transfers`.

Because I'm not sure if it's perfect. and in order to test and confirm, it can't execute with single query because Solana data is too heavy to run with one query.

I'm going to make it `opensea_solana.events` after testing and modifying if needed.

The point is, I want to keep the table in operation until the table in development is complete. If you let me know if there's any other way, I'll apply like that.

*For Dune Engine V2*
I've checked that:

* [x] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [x] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [ ] if adding a new model, I added a test
* [x] the filename is unique and ends with .sql
* [x] each sql file is a select statement and has only one view, table or function defined  
* [x] column names are `lowercase_snake_cased`

When you are ready for a review, tag duneanalytics/data-experience. We will re-open your forked pull request as an internal pull request. Then your spells will run in dbt and the logs will be avaiable in Github Actions DBT Slim CI. This job will only run the models and tests changed by your PR compared to the production project.

### CODE REVIEW

**Comment by sohwak** [comment]
also added opensea trades abstraction on Polygon (Dune v1)

**Comment by sohwak** [comment]
example: 
- opensea-solana query : https://dune.com/queries/1141087
- opensea-polygon query : https://dune.com/queries/1146806

**Comment by sohwak** [comment]
forgot to mention one thing: for Solana query, I execute it for just "1 day" duration, and it took around 2 min to get result.

**Comment by jeff-dude** [comment]
> also added opensea trades abstraction on Polygon (Dune v1)

i'd suggest pulling the polygon portion out of this PR and submitting a separate PR with just that code, i'll be able to merge it in quicker, then we can focus on spellbook items here

**Comment by jeff-dude** [comment]
in regards to your comment on putting in a 'dummy' name for the object until it's built and tested, i think we can explore that as a last resort, but we should try to test via the dune web app query as much as possible and feel confident in full historical. for instance, you have the query set to 1 day, maybe you can expand it to larger timeframe (a week, a month) and test those results and get to level of comfort you are looking for.

worst case scenario, if tested a full month (and maybe even month timeframes multiple times for different months) and still find bugs, we can always rebuild later.

**Comment by jeff-dude** [comment]
> > also added opensea trades abstraction on Polygon (Dune v1)
> 
> i'd suggest pulling the polygon portion out of this PR and submitting a separate PR with just that code, i'll be able to merge it in quicker, then we can focus on spellbook items here

fyi, i'm running the polygon script on v1 behind the scenes, but i still suggest to pull the code out of this branch/PR and put in it's own branch/PR, that way i can close it out. i pushed one change to this branch, so be sure to refresh locally, then create new

**Comment by sohwak** [comment]
Thank you for letting me know.

I will separate PR for Dune v1 and Spellbook. I was going to do that, but I was not used to it and I thought it would be no problem once.

As for the test, I will try to test it if possible. but for solana, the query does not run in more than 5 days. I think it's probably processing too much data. I'm doing my best for the query when I wrote but I'm worried if I get it wrong. In any case, the current `opensea_solana.events` is the table already in use, so I am afraid that it will affect other dashboards when it has wrong data. I will happy if you give me more note about this part.

I will close this PR and open separated PRs

**Pull request closed without merging**
