### PR TITLE
update erc20.tokens (Add PSP)

### PR DESCRIPTION
**Pull request by bh2smith**
Given the recent launch of PSP it seems like another good time to update the token list.

### CODE REVIEW

**Comment by masquot** [comment]
Thank you for updating the token list @bh2smith

**Review by masquot — APPROVED** [review]

**Comment by bh2smith** [comment]
No problem. I would love if you shared your technique for sorting this list.

**Comment by masquot** [comment]
> No problem. I would love if you shared your technique for sorting this list.

Sure. I do it in 2 steps (I'm on linux):
1. `sed -n '/\\\\/ p' tokens.sql | sort -k2 > sorted.sql`
2. Manually copy-paste the sorted tokens back into `tokens.sql`

**Comment by bh2smith** [comment]
Thanks @masquot - that is boss. I will remember (or rather, come back here) for next time.

**Pull request merged**
