### PR TITLE
Add eth_transfers to OP2

### PR DESCRIPTION
**Pull request by MSilb7**
Re-creating https://github.com/duneanalytics/abstractions/pull/943 with updates:
- Added the placeholder ETH address to match indices + make joins to prices tables easier.

I've checked that:

* [ ] the query produces the intended results
* [ ] the folder name matches the schema name
* [ ] the schema name exists in Dune
* [ ] views are prefixed with `view_`, functions with `fn_`.
* [ ] the filename matches the defined view, table or function and ends with .sql
* [ ] each file has only one view, table or function defined  
* [ ] column names are `lowercase_snake_cased`

### CODE REVIEW

**Comment by jeff-dude** [comment]
@MSilb7 please review latest changes i pushed to your function file & ensure the tweaks to make it run are as expected. once you confirm, i can look to load the data.

**Comment by MSilb7** [comment]
> @MSilb7 please review latest changes i pushed to your function file & ensure the tweaks to make it run are as expected. once you confirm, i can look to load the data.

Hi, yes looks good, thank you for the updates! Missed some updates after copy and pasting inserts from another query. @jeff-dude

**Review by jeff-dude — CHANGES_REQUESTED** [review]
@MSilb7 there appears to be duplicates in the data trying to load eth_transfers via the function. here is reference query:

select *
, count(1)
from 
(
	SELECT r.tx_hash
	, r.tx_index 
	FROM optimism."traces" r
	INNER JOIN optimism.transactions t
            ON t.hash = r.tx_hash
			AND t.block_time >= '2021-12-25'
		    AND t.block_time < '2022-01-01'
    WHERE (r.call_type NOT IN ('delegatecall', 'callcode', 'staticcall') or r.call_type is null)
    AND r."tx_success" = true
    AND r.success = true
    AND r.value > 0    
    AND r.block_time >= '2021-12-25'
    AND r.block_time < '2022-01-01'	
) x 
group by x.tx_hash
, x.tx_index
having count(1) > 1
order by 3 desc
;

this causes errors due to PK on table

**Comment by MSilb7** [comment]
> @MSilb7 there appears to be duplicates in the data trying to load eth_transfers via the function. here is reference query:
> 
> select * , count(1) from ( SELECT r.tx_hash , r.tx_index FROM optimism."traces" r INNER JOIN optimism.transactions t ON t.hash = r.tx_hash AND t.block_time >= '2021-12-25' AND t.block_time < '2022-01-01' WHERE (r.call_type NOT IN ('delegatecall', 'callcode', 'staticcall') or r.call_type is null) AND r."tx_success" = true AND r.success = true AND r.value > 0 AND r.block_time >= '2021-12-25' AND r.block_time < '2022-01-01' ) x group by x.tx_hash , x.tx_index having count(1) > 1 order by 3 desc ;
> 
> this causes errors due to PK on table

Hi, yes found the issue. Should've used trace_address instead of tx_index. Fixing now!

**Comment by MSilb7** [comment]
Made some updates and tested locally. Should be good to go now @jeff-dude ! Appreciate the patience with me haha.

**Review by jeff-dude — APPROVED** [review]
thank you for the changes @MSilb7 this table is now live

**Pull request merged**
