### PR TITLE
Update coingecko.yaml

### PR DESCRIPTION
**Pull request by 0xroll**
adding yam token

https://www.coingecko.com/en/coins/yam-v2
https://www.coingecko.com/en/coins/yam

I've checked that:

* [ ] the query produces the intended results
* [ ] the folder name matches the schema name
* [ ] the schema name exists in Dune
* [ ] views are prefixed with `view_`, functions with `fn_`.
* [ ] the filename matches the defined view, table or function and ends with .sql
* [ ] each file has only one view, table or function defined  
* [ ] column names are `lowercase_snake_cased`

### CODE REVIEW

**Review by jeff-dude — CHANGES_REQUESTED** [review]

**Comment by jeff-dude** [comment]
apologies @0xroll i did not submit my review. please see requested changes above. i'm getting an error when looking at coin gecko api for 'yam' id value

**Comment by 0xroll** [comment]
hey @jeff-dude ! apologies it is supposed to be yam-2 instead

https://api.coingecko.com/api/v3/coins/yam-2

**Review by jeff-dude — APPROVED** [review]
@0xroll all set, thank you 👍

**Comment by 0xroll** [comment]
thanks @jeff-dude !

ive tried to query this but i dont see any result, any idea why? could it be due to the coingecko data only includes for ethereum address?

https://dune.com/queries/683167

**Comment by jeff-dude** [comment]
unfortunately, in the current system, we don't have a workaround for this scenario where it returns ethereum address. i'm told the new v2 engine will not run into this issue though. we can try again then, if needed.

**Pull request merged**
