### PR TITLE
Add shibaswap to dex.trades on ethereum

### PR DESCRIPTION
**Pull request by lolboysg**
Added Shibaswap to dex.trades table on Ethereum as requested in #599.
Results of the Shibaswap query can be checked at the dune_user_generated.shibaswap table.

I've checked that:

* [x] the query produces the intended results
* [x] the folder name matches the schema name
* [x] the schema name exists in Dune
* [x] views are prefixed with `view_`, functions with `fn_`.
* [x] the filename matches the defined view, table or function and ends with .sql
* [x] each file has only one view, table or function defined  
* [x] column names are `lowercase_snake_cased`

### CODE REVIEW

**Comment by lolboysg** [comment]
@masquot could you add as reviewer @dsalv ?

**Comment by lolboysg** [comment]
In the meantime @dsalv feel free to review it :)

**Comment by lolboysg** [comment]
thanks @jeff-dude I've totally forgot to push it

**Comment by jeff-dude** [comment]
> thanks @jeff-dude I've totally forgot to push it

sure thing. i'm working through getting this PR processed.

**Review by jeff-dude — APPROVED** [review]
@lolboysg thank you for the patience, shibaswap has been added to dex.trades and the cron jobs.

**Pull request merged**
