### PR TITLE
Add bep20 tokens 20220515

### PR DESCRIPTION
**Pull request by kunwh**
Added more bep20 tokens and updated conpaprika.yaml.

I've checked that:

* [x] the query produces the intended results
* [x] the folder name matches the schema name
* [x] the schema name exists in Dune
* [x] views are prefixed with `view_`, functions with `fn_`.
* [x] the filename matches the defined view, table or function and ends with .sql
* [x] each file has only one view, table or function defined  
* [x] column names are `lowercase_snake_cased`

### CODE REVIEW

**Review by jeff-dude — APPROVED** [review]
@kunwh tokens added 👍  as for the prices file, it's difficult to check that many new additions, please keep a close eye on the end result and open a new PR if any fix is needed

**Comment by jeff-dude** [comment]
fyi -- coinpaprika has changed their API, which means some updates on our side. we may end up needing to revert this PR and revisit in the near future. you likely won't see the new tokens at this time.

**Comment by kunwh** [comment]
@jeff-dude Couple follow-up questions: 
For the bep20 tokens, should I create a separated PR? 
For coinpaprika.yaml, is it possible to change to coingecko.yaml (same as what polygen one using)? 
Thanks!

**Comment by jeff-dude** [comment]
> @jeff-dude Couple follow-up questions: For the bep20 tokens, should I create a separated PR? For coinpaprika.yaml, is it possible to change to coingecko.yaml (same as what polygen one using)? Thanks!

apologies for the confusion, the tokens shouldn't be affected, those should have been deployed just fine. let me know if you see otherwise. it's only the prices file with an issue.

at this time, coingecko isn't set up to be used in this scenario. our team is working on the new solution & we'll be sure to work with you to get new prices in when ready.

**Pull request merged**
