### PR TITLE
Add swapr to dex.trades on ethereum

### PR DESCRIPTION
**Pull request by lolboysg**
Added Swapr to dex.trades table on Ethereum as requested in #601.
Results of the Swapr query can be checked at the dune_user_generated.swapr table.

You can check that the results are right by comparing to the official swapr stats https://dxstats.eth.link/#/home

I've checked that:

* [X] the query produces the intended results
* [X] the folder name matches the schema name
* [X] the schema name exists in Dune
* [X] views are prefixed with `view_`, functions with `fn_`.
* [X] the filename matches the defined view, table or function and ends with .sql
* [X] each file has only one view, table or function defined  
* [X] column names are `lowercase_snake_cased`

### CODE REVIEW

**Comment by jeff-dude** [comment]
@lolboysg thank you for the new request. i'm looking at this with the team. there was a prior PR #622 for Swapr which was closed. ensuring the changes are what is needed

**Comment by jeff-dude** [comment]
@lolboysg token_a should be token bought, looks like you may need to flip logic for token a/b assignment.

comparing to uniswap entries in dex trades:
select *
from dex.trades
where lower(project) like '%uniswap%'
and tx_hash = '\xfd6abe304f5332582f76d8f0bdfe9f8e4fe1d8a4ccf5079a7826ba6602ee97c4'

https://etherscan.io/tx/0xfd6abe304f5332582f76d8f0bdfe9f8e4fe1d8a4ccf5079a7826ba6602ee97c4

**Comment by jeff-dude** [comment]
@lolboysg token_a should be token bought, looks like you may need to flip logic for token a/b assignment.

comparing to uniswap entries in dex trades:
select *
from dex.trades
where lower(project) like '%uniswap%'
and tx_hash = '\xfd6abe304f5332582f76d8f0bdfe9f8e4fe1d8a4ccf5079a7826ba6602ee97c4'

https://etherscan.io/tx/0xfd6abe304f5332582f76d8f0bdfe9f8e4fe1d8a4ccf5079a7826ba6602ee97c4

**Comment by lolboysg** [comment]
I think the logic is correct as the token_a is the token being bought and token_b is the token being sold.
You can see a example in this [request](https://dune.xyz/queries/608289) which is [this](https://etherscan.io/tx/0x29395f01f2e3800bb60adadb41a6d43f9e0c0c437b9f78cb5aff4caa313e1496) transaction in etherscan

**Comment by jeff-dude** [comment]
> I think the logic is correct as the token_a is the token being bought and token_b is the token being sold. You can see a example in this [request](https://dune.xyz/queries/608289) which is [this](https://etherscan.io/tx/0x29395f01f2e3800bb60adadb41a6d43f9e0c0c437b9f78cb5aff4caa313e1496) transaction in etherscan

makes sense. i've loaded the history and enabled the cron job. thank you for the new dex addition.

**Review by jeff-dude — APPROVED** [review]

**Pull request merged**
