### PR TITLE
Add cex addresses

### PR DESCRIPTION
**Pull request by hildobby**
Brief comments on the purpose of your changes:
Added a list of known CEX addresses I could identify

*For Dune Engine V2*
I've checked that:

* [X] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [X] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [ ] if adding a new model, I added a test
* [X] the filename is unique and ends with .sql
* [X] each sql file is a select statement and has only one view, table or function defined  
* [X] column names are `lowercase_snake_cased`

When you are ready for a review, tag duneanalytics/data-experience. We will re-open your forked pull request as an internal pull request. Then your spells will run in dbt and the logs will be avaiable in Github Actions DBT Slim CI. This job will only run the models and tests changed by your PR compared to the production project.

### CODE REVIEW

**Comment by jeff-dude** [comment]
proposed some updates via a commit. curious to hear input @dot2dotseurat @hildobby if you think this is good, or we can easily revert as needed 👍

**Comment by hildobby** [comment]
> proposed some updates via a commit. curious to hear input @dot2dotseurat @hildobby if you think this is good, or we can easily revert as needed 👍

I thought about this and while yes I did check solely on ethereum, those addresses are often use across chains so I kept it without ethereum mentioned but I'm not sure what the best route is here 🤔 

Also, I see you re;oved the schema='cex' but I discussed this with @dot2dotseurat and we said that keeping the schema='cex' would be best so we have cex.addresses (but the list remains in the addresses folder). This is because in the future I plan on (and im sure others also will) adding stuff like bridges.adddresses for example and it is likely that other abstractions will appear under the bridges schema.

**Comment by jeff-dude** [comment]
> > proposed some updates via a commit. curious to hear input @dot2dotseurat @hildobby if you think this is good, or we can easily revert as needed 👍
> 
> I thought about this and while yes I did check solely on ethereum, those addresses are often use across chains so I kept it without ethereum mentioned but I'm not sure what the best route is here 🤔
> 
> Also, I see you re;oved the schema='cex' but I discussed this with @dot2dotseurat and we said that keeping the schema='cex' would be best so we have cex.addresses (but the list remains in the addresses folder). This is because in the future I plan on (and im sure others also will) adding stuff like bridges.adddresses for example and it is likely that other abstractions will appear under the bridges schema.

thank you for the context. no problem, happy to help revert. i figured the best way to ask questions was to look at it this way.

**Comment by dot2dotseurat** [comment]
@jeff-dude @hildobby just triggered the tests and things look good. Let's revert the schema back to `cex` so the table name can be `cex.addresses` and then this is good to go.

**Comment by jeff-dude** [comment]
pushed a commit to revert back to original code and naming standard, feel free to merge if looks good

**Review by jeff-dude — APPROVED** [review]

**Pull request merged**
