### PR TITLE
[dbt test] update nft tokens to 2022-06-04

### PR DESCRIPTION
**Pull request by dot2dotseurat**
@jeff-dude  I copied over @0xbitfly's work here so the CI tests would run. For context, we have an issue where commits from forked repos don't get picked up by our CI tool so I just made a new branch off of your branch. 

That test caught a missing comma in the v2 version of the tokens table. I pushed a small commit that fixes that issue. 

If you want to test your V2 contributions, when you run `dbt compile` (after installing it) and it creates a new folder called target with your compiled SQL.  You can copy the SQL there and run it directly on dune.com to check it. 

I've checked that:

* [x] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [n/a] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [x] the directory tree matches the pattern /sector/blockchain/ e.g. /tokens/ethereum
* [n/a] if adding a new model, I added a test
* [x] the filename is unique and ends with .sql
* [x] each file has only one view, table or function defined  
* [x] column names are `lowercase_snake_cased`

### CODE REVIEW

**Comment by 0xbitfly** [comment]
Nice job! So for the v2 version PR, I should check the dbt compile result sql on dune?

**Comment by dot2dotseurat** [comment]
> 

yep, let me know if you have questions or run into issues with that. what should happen is your query is compiled and you can run it directly on dune.com to test.

side note: 
it's a little more complicated when you are referencing another view/table that you are creating in the dbt project because your personal schema gets prepended to the view/table name so nft.trades would become wizard_nft.trades etc but we are working on a fix for that. the prepended schema thing is a feature in dbt so colleagues can work on the same table without collisions but for us since everyone it working on dune.com it's a little wonky. 

but in general yes. compile and run on dune.com. if you get an error about a table not existing, check to see if it's because the wizard schema is prepended to a table name.

**Comment by jeff-dude** [comment]
fyi the v1 engine tokens table has been refreshed with the updated file here

**Review by jeff-dude — APPROVED** [review]
@dot2dotseurat apologies if you were waiting on my approval, but all set from my side, if you're good 👍

**Pull request merged**
