### PR TITLE
Mistx flashdex

### PR DESCRIPTION
**Pull request by ripples3**
I've checked that:

* [x] the query produces the intended results
* [x] the folder name matches the schema name
* [x] the schema name exists in Dune
* [x] views are prefixed with `view_`, functions with `fn_`.
* [x] the filename matches the defined view, table or function and ends with .sql
* [x] each file has only one view, table or function defined  
* [x] column names are `lowercase_snake_cased`

For comparison:
Query using insert_mistx.sql: https://duneanalytics.com/queries/93937
image

Query using dex.trades:         https://duneanalytics.com/queries/93965      
image

Note: mistX routes the trade to either Uniswap or Sushiswap

### CODE REVIEW

**Comment by markusbkoch** [comment]
Thanks for this. The DEX category is reserved for primary source of liquidity, like Uniswap suhsiswap, balancer. Protocols that route trades to DEXs should be categorized as Aggregators. See insert_1inch for an example.

**Comment by ripples3** [comment]
Hi Mark, thank you for checking. I update the category now.

**Comment by ripples3** [comment]
@markusbkoch let me know if the changes I made are enough. Thank you!

**Review by antonio-mendes — APPROVED** [review]
Looks good @ripples3 🙇

**Pull request merged**
