### PR TITLE
Create bucketsclub.sql

### PR DESCRIPTION
**Pull request by karansingh87**
Add Buckets Club traits

I've checked that:

* [x] the query produces the intended results
* [ ] the folder name matches the schema name
* [ ] the schema name exists in Dune
* [ ] views are prefixed with `view_`, functions with `fn_`.
* [ ] the filename matches the defined view, table or function and ends with .sql
* [x] each file has only one view, table or function defined  
* [x] column names are `lowercase_snake_cased`

### CODE REVIEW

**Review by musama99 — APPROVED** [review]

**Review by masquot — CHANGES_REQUESTED** [review]
Thanks so much for creating this PR to add Buckets Club traits @karansingh87.

I noticed that the values for `nft_contract_address` and `project_name` are the same in every row. Maybe these columns can be removed as the name is implicit in the name of the table `bucketsclub.body`?

**Comment by karansingh87** [comment]
> 

Thanks for reviewing @masquot. Updated the code with proposed suggestions.

**Comment by masquot** [comment]
Great. Thank you @karansingh87. Tried to write to DB and got an error as some rows have the same `nft_token_id`.

Looked into this and discovered many rows where ID in URL does not match `nft_token_id`. Here are just some examples:

```
('Eagle Buckets','https://opensea.io/assets/0x025f45bb7e08abea27a3c6a9cfb8d2acc2f6a134/651',151),
    ('Buckets S. Thompson','https://opensea.io/assets/0x025f45bb7e08abea27a3c6a9cfb8d2acc2f6a134/653',153),
    ('Agave Buckets','https://opensea.io/assets/0x025f45bb7e08abea27a3c6a9cfb8d2acc2f6a134/985',485),
    ('Oakley Bucket Hat Buckets','https://opensea.io/assets/0x025f45bb7e08abea27a3c6a9cfb8d2acc2f6a134/796',296),
    ('Dancing Buckets (Green)','https://opensea.io/assets/0x025f45bb7e08abea27a3c6a9cfb8d2acc2f6a134/584',84),
    ('King Buckets','https://opensea.io/assets/0x025f45bb7e08abea27a3c6a9cfb8d2acc2f6a134/587',87),
    ('Raccoon Buckets','https://opensea.io/assets/0x025f45bb7e08abea27a3c6a9cfb8d2acc2f6a134/592',92),
    ('Duderino Buckets','https://opensea.io/assets/0x025f45bb7e08abea27a3c6a9cfb8d2acc2f6a134/588',88),
    ('Mahan Buckets','https://opensea.io/assets/0x025f45bb7e08abea27a3c6a9cfb8d2acc2f6a134/589',89),
    ('Scottish Buckets','https://opensea.io/assets/0x025f45bb7e08abea27a3c6a9cfb8d2acc2f6a134/586',86),
    ('Aloha Buckets','https://opensea.io/assets/0x025f45bb7e08abea27a3c6a9cfb8d2acc2f6a134/596',96),
    ('Daly Buckets','https://opensea.io/assets/0x025f45bb7e08abea27a3c6a9cfb8d2acc2f6a134/583',83),
    ('King Buckets','https://opensea.io/assets/0x025f45bb7e08abea27a3c6a9cfb8d2acc2f6a134/509',9),
```

**Comment by karansingh87** [comment]
Oh wow. Thanks for reviewing this for me. I'll QC the database and ping you
when it's done. Appreciate it!

**Comment by karansingh87** [comment]
Hi,

I have updated the database with correct token_ids corresponding to the
os_link.

Hope this works. Thank you for bearing with me. This is my first time
playing with databases and making github pull requests, so I appreciate
your support!

Best,
Karan

**Review by masquot — APPROVED** [review]

**Comment by masquot** [comment]
You're welcome @karansingh87. Amazing that you first PR is Buckets Club on Dune!

Made some small fixes, and Buckets Club data is now accessible on Dune Ethereum :rocket:

**Comment by karansingh87** [comment]
Thanks so much. Already queried and visualized the data and it looks glorious! If you don't mind sharing, what were the errors? Would be nice to know so I can keep in mind in the future.

**Pull request merged**
