### PR TITLE
Replace trader_a values for 1inch in dex.trades

### PR DESCRIPTION
**Pull request by fatayri**
Brief comments on the purpose of your changes:
Currently in dex.trades trader_a and tx_from are exactly the same for 1inch transactions. With this PR we replace the trader_a with the "from" value from the trace, not the transaction.

*For Dune Engine V2*
I've checked that:

* [] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [ ] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [ ] if adding a new model, I added a test
* [ ] the filename is unique and ends with .sql
* [ ] each sql file is a select statement and has only one view, table or function defined  
* [ ] column names are `lowercase_snake_cased`

When you are ready for a review, tag duneanalytics/data-experience. We will re-open your forked pull request as an internal pull request. Then your spells will run in dbt and the logs will be avaiable in Github Actions DBT Slim CI. This job will only run the models and tests changed by your PR compared to the production project.

### CODE REVIEW

**Comment by jeff-dude** [comment]
thank you @fatayri for the PR. i assume this means you'd like to truncate dex trades for 1inch (attached script) and then reload fresh with the new field?

i can look to do that tomorrow, it'll take a good amount of time i'd imagine to reprocess, so the data will be gone for a bit.

**Comment by fatayri** [comment]
Hey @jeff-dude! Thanks for the prompt reply.

Do we actually have any other options other than truncating and replacing? If not, it should be fine to do it so.

**Comment by jeff-dude** [comment]
> Hey @jeff-dude! Thanks for the prompt reply.
> 
> Do we actually have any other options other than truncating and replacing? If not, it should be fine to do it so.

the other option is that you can supply an update statement here in the comments, but that may end up a bit complex with all the different project names, versions and categories contained within. it also may take even more time than a delete/reload.

let me know your thoughts between the two and i'll look to perform on monday morning

**Comment by fatayri** [comment]
Hey, sorry for the super long reply. We considered our options and decided that it might make more sense to truncate the values and fully rewrite it. But it's better to let it run over the weekend. 

If it's not too late for today and you have some spare time - it would be perfect. If not, we can run it next Friday.

**Comment by jeff-dude** [comment]
> Hey, sorry for the super long reply. We considered our options and decided that it might make more sense to truncate the values and fully rewrite it. But it's better to let it run over the weekend.
> 
> If it's not too late for today and you have some spare time - it would be perfect. If not, we can run it next Friday.

no problem, i'll look to do it over the weekend at some point

**Comment by jeff-dude** [comment]
this is still running and backfilling history, if anyone is noticing the data missing

**Review by jeff-dude — APPROVED** [review]
@fatayri this fix should be applied and backfilled again 👍

**Pull request merged**
