### PR TITLE
Add 1inch to dex.trades on polygon

### PR DESCRIPTION
**Pull request by lolboysg**
Added 1inch to dex.trades table on Polygon as requested in #606.
Results of the 1inch query can be checked at the dune_user_generated.oneinch table.

I've checked that:

* [x] the query produces the intended results
* [x] the folder name matches the schema name
* [x] the schema name exists in Dune
* [x] views are prefixed with `view_`, functions with `fn_`.
* [x] the filename matches the defined view, table or function and ends with .sql
* [x] each file has only one view, table or function defined  
* [x] column names are `lowercase_snake_cased`

### CODE REVIEW

**Comment by masquot** [comment]
@k06a. Maybe you or someone of the team would like to review this one?

**Comment by nata-omutyanka** [comment]
1.	37% of swaps don’t have names of tokens (only 9% of Ethereum swaps don’t have it)
2.	2.5% of swaps has two rows. Maybe they will overstate volume (These transactions are more difficult then just swaps)

**Comment by lolboysg** [comment]
I am looking through that

**Comment by lolboysg** [comment]
would it be possible to have an example of a swap that has two rows ?

**Comment by nata-omutyanka** [comment]
For example \x00cecbd9332c235b07f8088b18072c6dbb0d4ed19faf3d4b0756cb63e2e90a6c
\x096ffb3f726dfbeef5bb2f1c62dce4416d26c112fb8871f633003a3e4da70d19

**Comment by lolboysg** [comment]
To keep you updated I've requested in another PR #648 . It will resolve the missing swaps that don't have the names of tokens. And I changed a bit the trade_id so that you can only query all rows where trade_id = 1 to don't get any duplicates

**Comment by lolboysg** [comment]
ok just to keep you updated @nata-omutyanka the PR has been merged so now it should be good :)

**Comment by k06a** [comment]
What's the state of this PR?

**Comment by lolboysg** [comment]
I think everything is good

**Pull request merged**
