### PR TITLE
Prices Lookup after insert_uniswap_v3.sql

### PR DESCRIPTION
**Pull request by MSilb7**
Temporary fix to run the prices insert after the Uniswap DEX trades update completes.

I've checked that:

* [ ] the query produces the intended results
* [ ] the folder name matches the schema name
* [ ] the schema name exists in Dune
* [ ] views are prefixed with `view_`, functions with `fn_`.
* [ ] the filename matches the defined view, table or function and ends with .sql
* [ ] each file has only one view, table or function defined  
* [ ] column names are `lowercase_snake_cased`

### CODE REVIEW

**Comment by masquot** [comment]
Thank you @MSilb7. Tested this manually first. While it runs to completion, it runs very slowly. Checking database health with the engineers. Will keep you posted.

**Comment by masquot** [comment]
Our engineers started a maintenance job yesterday and it is still running. Sorry for the inconvenience @MSilb7

**Comment by MSilb7** [comment]
> Our engineers started a maintenance job yesterday and it is still running. Sorry for the inconvenience @MSilb7

All good, do you have a sense of if its the dex run or the prices run that's slow?

**Comment by masquot** [comment]
> > Our engineers started a maintenance job yesterday and it is still running. Sorry for the inconvenience @MSilb7
> 
> All good, do you have a sense of if its the dex run or the prices run that's slow?

It s a `dex.trades` DB maintenance job that has been running for days. We expect this job to finish over the weekend. I will debrief with the engineer once finished and check in with you at that time.

**Comment by masquot** [comment]
Fixed in #865

**Pull request closed without merging**
