### PR TITLE
Fix cron in insert_l1_gas_price_oracle_updates - Optimism2

### PR DESCRIPTION
**Pull request by MSilb7**
I've checked that:

* [ ] the query produces the intended results
* [ ] the folder name matches the schema name
* [ ] the schema name exists in Dune
* [ ] views are prefixed with `view_`, functions with `fn_`.
* [ ] the filename matches the defined view, table or function and ends with .sql
* [ ] each file has only one view, table or function defined  
* [ ] column names are `lowercase_snake_cased`

### CODE REVIEW

**Review by masquot — APPROVED** [review]
This update has been implemented as well.

**Comment by MSilb7** [comment]
Hm, still not seeing the table update beyond the initial 1000, any ideas? Maybe force a few more blocks in and see if it starts functioning?

**Comment by masquot** [comment]
The code works fine when the `start_block` input equals 1:
`SELECT ovm2.insert_l1_gas_price_oracle_updates(1,10000);`

But it fails when this input is bigger than 1:
`SELECT ovm2.insert_l1_gas_price_oracle_updates(100,10000);`
Error message:
```
ERROR:  null value in column "l1_gas_price" of relation "l1_gas_price_oracle_updates" violates not-null constraint
DETAIL:  Failing row contains (100, null, null).
```

**Comment by MSilb7** [comment]
> The code works fine when the `start_block` input equals 1: `SELECT ovm2.insert_l1_gas_price_oracle_updates(1,10000);`
> 
> But it fails when this input is bigger than 1: `SELECT ovm2.insert_l1_gas_price_oracle_updates(100,10000);` Error message:
> 
> ```
> ERROR:  null value in column "l1_gas_price" of relation "l1_gas_price_oracle_updates" violates not-null constraint
> DETAIL:  Failing row contains (100, null, null).
> ```

Ah yeah I think that's a weird edge case since I had the second insert start exactly at 100 rather than give a buffer. For future-proofing, I should add something where it defaults to pulling the most recent L1 Gas Price if there are no updates between the start block and first new update. On it.

**Comment by MSilb7** [comment]
Figured out this issue, PRd here: https://github.com/duneanalytics/abstractions/pull/695

**Pull request merged**
