### PR TITLE
Create CARDS.sql

### PR DESCRIPTION
**Pull request by msg3**
I've checked that:

* [x] the query produces the intended results
* [x] the folder name matches the schema name
* [x] the schema name exists in Dune
* [x] views are prefixed with `view_`, functions with `fn_`.
* [x] the filename matches the defined view, table or function and ends with .sql
* [x] each file has only one view, table or function defined  
* [x] column names are `lowercase_snake_cased`

### CODE REVIEW

**Comment by msg3** [comment]
Goal is to have the cards.sql file appear similar to wicked_cranium_traits.sql

**Review by antonio-mendes — CHANGES_REQUESTED** [review]
Hey @msg3 ,

I need to ask you a few quick changes before merging and deploying this:
- Create a schema explicitly like you see here: https://github.com/duneanalytics/abstractions/blob/5cd85640e8f5faf029398d468046410f125be399/ethereum/nft_traits/rumblekong_stats.sql#L1
- Give the schema and table meaningful names not just `mytable`
- Don't insert the data by using the `INSERT INTO` statement over and over, try to do something like this: https://github.com/duneanalytics/abstractions/blob/5cd85640e8f5faf029398d468046410f125be399/ethereum/nft_traits/rumblekong_stats.sql#L13
- Create an index for `token_id` it'll probably end up being useful for most of your queries:  https://github.com/duneanalytics/abstractions/blob/5cd85640e8f5faf029398d468046410f125be399/ethereum/nft_traits/rumblekong_stats.sql#L10015

Let me know if you run into any issues 👍

**Comment by msg3** [comment]
@antonio-mendes per your request, all changes made and file name updated to wrappedstrikers_stats.sql

**Review by antonio-mendes — APPROVED** [review]
Hey again @msg3 ,

Thanks for the fixes, I had to do a bit of a manual cleanup still but I've deployed your data and you can now query it 👍  Let me know if it works out.

For future reference, main things I've changed:
- put the file in the correct folder
- you created a schema called `wrappedstrikers` but there was already a schema called `wrapped_strikers` so I used that instead
- cleaned up the file a bit and fixes a few small things 
- fixed index creation statement
- used some SQL some best practices (lower case name for variables etc)

Hope this helps out in future submissions 🙏 ! 

Cheers and happy querying

**Pull request merged**
