### PR TITLE
add CitaDAO KNIGHT token to dataset

### PR DESCRIPTION
**Pull request by ethanow**
Brief comments on the purpose of your changes:

*For Dune Engine V2*
I've checked that:

* [ ] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [ ] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [ ] if adding a new model, I added a test
* [ ] the filename is unique and ends with .sql
* [ ] each sql file is a select statement and has only one view, table or function defined  
* [ ] column names are `lowercase_snake_cased`

When you are ready for a review, tag duneanalytics/data-experience. We will re-open your forked pull request as an internal pull request. Then your spells will run in dbt and the logs will be avaiable in Github Actions DBT Slim CI. This job will only run the models and tests changed by your PR compared to the production project.

### CODE REVIEW

**Comment by jeff-dude** [comment]
thank you for the PR @ethanow -- it appears the token is inactive on coinpaprika:
https://api.coinpaprika.com/v1/coins/knight-citadao

note the is_active flag. is this expected? i believe with this status, new prices won't flow in

**Comment by jeff-dude** [comment]
> thank you for the PR @ethanow -- it appears the token is inactive on coinpaprika: https://api.coinpaprika.com/v1/coins/knight-citadao
> 
> note the is_active flag. is this expected? i believe with this status, new prices won't flow in

could potentially look to reactivate here?
https://coinpaprika.com/add/

**Comment by ethanow** [comment]
> > thank you for the PR @ethanow -- it appears the token is inactive on coinpaprika: https://api.coinpaprika.com/v1/coins/knight-citadao
> > note the is_active flag. is this expected? i believe with this status, new prices won't flow in
> 
> could potentially look to reactivate here? https://coinpaprika.com/add/

Thanks @jeff-dude. Submitted the request on coinpaprika. 

It's active on coingecko API: https://api.coingecko.com/api/v3/simple/token_price/ethereum?contract_addresses=0x3541a5c1b04adaba0b83f161747815cd7b1516bc&vs_currencies=usd

**Comment by jeff-dude** [comment]
> > > thank you for the PR @ethanow -- it appears the token is inactive on coinpaprika: https://api.coinpaprika.com/v1/coins/knight-citadao
> > > note the is_active flag. is this expected? i believe with this status, new prices won't flow in
> > 
> > 
> > could potentially look to reactivate here? https://coinpaprika.com/add/
> 
> Thanks @jeff-dude. Submitted the request on coinpaprika.
> 
> It's active on coingecko API: https://api.coingecko.com/api/v3/simple/token_price/ethereum?contract_addresses=0x3541a5c1b04adaba0b83f161747815cd7b1516bc&vs_currencies=usd

thank you for submitting the request! we'll let this sit for a bit until that's ready.

at this time, we don't have the infrastructure in place to read coingecko price feeds into ethereum db specifically. we may have redesign around prices in the future. we'll be sure to let the community know.

**Comment by jeff-dude** [comment]
as of this morning, it appears to still be inactive. i can continue to monitor or let me know via comment if notified from coinpaprika team.

**Comment by jeff-dude** [comment]
closing for now, can be new PR when ready through API

**Pull request closed without merging**
