### PR TITLE
Add Element to NFT aggregator list on Ethereum, BNB, Avalanche & Polygon for v2

### PR DESCRIPTION
**Pull request by hildobby**
Brief comments on the purpose of your changes:

Added Element NFT Marketplace to the list of NFT aggregators on Ethereum, BNB, Avalanche & Polygon.

*For Dune Engine V2*
I've checked that:

* [X] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [X] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [X] if adding a new model, I added a test
* [X] the filename is unique and ends with .sql
* [X] each sql file is a select statement and has only one view, table or function defined  
* [X] column names are `lowercase_snake_cased`

When you are ready for a review, tag duneanalytics/data-experience. We will re-open your forked pull request as an internal pull request. Then your spells will run in dbt and the logs will be avaiable in Github Actions DBT Slim CI. This job will only run the models and tests changed by your PR compared to the production project.

### CODE REVIEW

**Review by jeff-dude — CHANGES_REQUESTED** [review]
@hildobby these files look good -- just double checking with @soispoke that this fits how he envisioned expanding aggregator metadata models

can you also add updates to the following:
1. alter_table_properties macro -- add the views similar to ethereum version, also the 'run query' at bottom
2. dbt_project yaml file -- add new file directories under nft block similar to ethereum, ensure schema name is as intended

**Comment by hildobby** [comment]
> @hildobby these files look good -- just double checking with @soispoke that this fits how he envisioned expanding aggregator metadata models
> 
> can you also add updates to the following:
> 
> 1. alter_table_properties macro -- add the views similar to ethereum version, also the 'run query' at bottom
> 2. dbt_project yaml file -- add new file directories under nft block similar to ethereum, ensure schema name is as intended

Just added all of those, let me know if it's missing anything else!

**Comment by jeff-dude** [comment]
> > @hildobby these files look good -- just double checking with @soispoke that this fits how he envisioned expanding aggregator metadata models
> > can you also add updates to the following:
> > 
> > 1. alter_table_properties macro -- add the views similar to ethereum version, also the 'run query' at bottom
> > 2. dbt_project yaml file -- add new file directories under nft block similar to ethereum, ensure schema name is as intended
> 
> Just added all of those, let me know if it's missing anything else!

in the alter table file, can you also add to the block at the bottom? that'll actually run the commands (similar to this: {% do run_query(nft_ethereum_aggregators) %})

**Comment by hildobby** [comment]
> > > @hildobby these files look good -- just double checking with @soispoke that this fits how he envisioned expanding aggregator metadata models
> > > can you also add updates to the following:
> > > 
> > > 1. alter_table_properties macro -- add the views similar to ethereum version, also the 'run query' at bottom
> > > 2. dbt_project yaml file -- add new file directories under nft block similar to ethereum, ensure schema name is as intended
> > 
> > 
> > Just added all of those, let me know if it's missing anything else!
> 
> in the alter table file, can you also add to the block at the bottom? that'll actually run the commands (similar to this: {% do run_query(nft_ethereum_aggregators) %})

Done ✅

**Review by jeff-dude — APPROVED** [review]
thanks for the quick updates. lgtm. i'll let @soispoke give a final glance when he's ready in his time zone, but i'll approve on my side

**Comment by soispoke** [comment]
Just had a look, looks good to me @jeff-dude !

**Pull request merged**
