### PR TITLE
dex.trades: add dodo aggregator

### PR DESCRIPTION
**Pull request by kevinxzhang**
I've checked that:

* [x] the query produces the intended results
* [x] the folder name matches the schema name
* [x] the schema name exists in Dune
* [x] views are prefixed with `view_`, functions with `fn_`.
* [x] the filename matches the defined view, table or function and ends with .sql
* [x] each file has only one view, table or function defined  
* [x] column names are `lowercase_snake_cased`

### CODE REVIEW

**Comment by kevinxzhang** [comment]
@milkyklim Hello milkyklim, another pr to add data of dodo aggregator to dex.trades. Trouble you to review it. Thank you so much.

**Comment by milkyklim** [comment]
@kevinxzhang how is this PR different from this part of `dex.trades.dodo` https://github.com/duneanalytics/abstractions/blob/master/ethereum/dex/trades/insert_dodo.sql#L107-L169 ?

**Comment by kevinxzhang** [comment]
> @kevinxzhang how is this PR different from this part of `dex.trades.dodo` https://github.com/duneanalytics/abstractions/blob/master/ethereum/dex/trades/insert_dodo.sql#L107-L169 ?

Hi milkyklim, this part of data belongs to aggregated data, I just want to show these data on the aggregator table in DEX metrics.

**Comment by 0xBoxer** [comment]
Hey @kevinxzhang, I have ran some tests and there seems to be something that is not quite working properly here.

There is quite a few trades that are missing usd.amounts due to $dodo not having a price, I'll write a PR to include the dodo price in our prices table for that.

Furthermore there is quite a few trades which are basically dodo <> dodo trades, I am not sure what's happening in your smart contracts there, but it would be great if you could filter those out or at least explain why they should be included.
example:
[https://etherscan.io/tx/0x92a4d91fb1f3d907c28489e4c005ea35af1e6c145133069bfc1d86c8f5af1cbd](https://etherscan.io/tx/0x92a4d91fb1f3d907c28489e4c005ea35af1e6c145133069bfc1d86c8f5af1cbd) 

query that filters for this: 
https://duneanalytics.com/queries/65048

**Review by 0xBoxer — CHANGES_REQUESTED** [review]
See previous comment, just a status update

**Comment by masquot** [comment]
See #556

**Pull request closed without merging**
