### PR TITLE
Added new modular views

### PR DESCRIPTION
**Pull request by ThreeStepCapital**
*view_all_owners.sql
Table to view all owners of all vaults. 

*view_balances_by_day.sql
Table to view balances of collateral tokens by day

*view_contract_token_label.sql
Table to show what contract corresponds to what underlying collateral token type

*view_evt_aggregate.sql
Table for all transactions

*view_evt_approval.sql
Table to see all approval transactions

*view_evt_borrow_mai.sql
Table to see all borrow mai transactions

*view_evt_create_vault.sql
Table to see all create vault transactions

*view_evt_deposit_collateral.sql
Table for all transactions to deposit collateral 

*view_evt_destroy_vault.sql
Table for all transactions to destroy a vault

*view_evt_liquidate_vault.sql
Table for all liquidation of vault events

*view_evt_ownership_transfer.sql
Table for all ownership transfer transactions

*view_evt_payback_mai.sql
Table for all paybackmai transactions

*view_evt_transfer.sql
Table for all transfer transactions

*view_evt_transfer_vault.sql
Table for all transfer vault transactions

*view_evt_withdraw_collateral.sql
Table for all withdraw collateral transactions

I've checked that:

* [x] the query produces the intended results
* [x] the folder name matches the schema name
* [x] the schema name exists in Dune
* [x] views are prefixed with `view_`, functions with `fn_`.
* [x] the filename matches the defined view, table or function and ends with .sql
* [x] each file has only one view, table or function defined  
* [x] column names are `lowercase_snake_cased`

### CODE REVIEW

**Comment by masquot** [comment]
Thank you @ThreeStepCapital. Looks like great work.

Please let us know:
- once this code is ready to be reviewed
- the order in which these files need to be written to our database

**Comment by ThreeStepCapital** [comment]
Hi @masquot 
Here is the order we'd like to be written to db: 

FIRST:
*view_evt_approval.sql
*view_evt_borrow_mai.sql
*view_evt_create_vault.sql
*view_evt_deposit_collateral.sql
*view_evt_destroy_vault.sql
*view_evt_liquidate_vault.sql
*view_evt_ownership_transfer.sql
*view_evt_payback_mai.sql
*view_evt_transfer.sql
*view_evt_transfer_vault.sql
*view_evt_withdraw_collateral.sql

SECOND:
*view_evt_aggregate.sql

THIRD: 
*view_contract_token_label.sql

FOURTH:
*view_all_owners.sql
*view_balances_by_day.sql

Thank you.

**Comment by masquot** [comment]
Thank you @ThreeStepCapital. The views from the first three steps have been created.

Now the materialized views from the 4th step are being created. Could take a while.

**Comment by ThreeStepCapital** [comment]
Hi @masquot - just wanted to follow up to see if the 4th step materialized views were able to be created. Thank you so much.

**Review by masquot — APPROVED** [review]
All is working. Updated the cron job for `view_balances_by_day` to run every hour at minute 3.

**Pull request merged**
