### PR TITLE
Update OP2 Dex Trades and Prices Logic

### PR DESCRIPTION
**Pull request by MSilb7**
Big PR to refine the prices table logic and get dex trades running again. New model:

- Use Chainlink price feeds as our base-level source of truth (i.e. ETH, USDC, DAI, USDT)
- Use DEX trades with tokens traded with tokens which have price feeds in order to get other token prices.
- Run a second-level price sweep to get the price list for a larger list of tokens.
- Run the chainlink update, prices update, dex inserts, second price sweep all within one `prices_and_trades_inserts.sql` to ensure no cross-dependencies.

This impacts where the 0x insert happens, so tagging @sui414 .

Definitely appreciate any feedback. It may make sense to rebuild the prices table from zero? Or we can just re-run the new insert over the whole table to make updates when needed.

I've checked that:

* [x] the query produces the intended results
* [ ] the folder name matches the schema name
* [ ] the schema name exists in Dune
* [ ] views are prefixed with `view_`, functions with `fn_`.
* [ ] the filename matches the defined view, table or function and ends with .sql
* [ ] each file has only one view, table or function defined  
* [ ] column names are `lowercase_snake_cased`

### CODE REVIEW

**Comment by masquot** [comment]
Thank you @MSilb7. This is amazing work. I think rebuilding the prices table from zero makes sense. 

I tried running the scripts in `chainlink` folder and there was a small inconsistency:
> psql:insert_price_feeds.sql: ERROR:  there is no unique or exclusion constraint matching the ON CONFLICT specification

**Comment by MSilb7** [comment]
> Thank you @MSilb7. This is amazing work. I think rebuilding the prices table from zero makes sense.
> 
> I tried running the scripts in `chainlink` folder and there was a small inconsistency:
> 
> > psql:insert_price_feeds.sql: ERROR:  there is no unique or exclusion constraint matching the ON CONFLICT specification

Ah yeah I had price in the unique descriptor for the table create when I shouldn't have. A last second update causing the issue again haha. Should be good to go now!

**Comment by MSilb7** [comment]
> Thank you @MSilb7
> 
> * [x]  setup of chainlink price feeds went fine
> * [ ]  backfill of new `insert_approx_prices_from_dex_data` does not run to completion for: `SELECT prices.insert_approx_prices_from_dex_data('2021-12-31', '2022-01-31')`. The script just 'hangs'. For the previous two periods of the backfill, the new insert function ran quikcly to completion. @MSilb7 Any ideas what might cause this? I tried twice.

We had a huge spike in transactions in the middle of Jan, so maybe it just becomes too much to run at once. I can split it up in to 2 and see if that helps.

**Comment by MSilb7** [comment]
Updated! @masquot

**Comment by masquot** [comment]
Thank you @MSilb7. I needed to go one step further and tried to run `prices.insert_approx_prices_from_dex_data` day by day. The inserts for all days go smoothly until :
> `SELECT prices.insert_approx_prices_from_dex_data('2022-01-23', '2022-01-24');`

Can you see anything out of the ordinary in the data for this day?

**Comment by MSilb7** [comment]
> 

I just checked and amount of trades gets up to 6M + per hour (which is invalid). I checked one of the hours and it looks like 1Inch trades are getting duplicated a few thousand times each, which I imagine is causing the issue. Checking on this now, but once we fix this it probably makes sense to delete 1inch trades and re-run.

**Comment by MSilb7** [comment]
I believe I solved the OneInch issue. The v4 router insert placed a NULL in the 'evt_index' and I think that screwed up our 'ON CONFLICT' resolution, since 'evt_index' was used as a unique identifier. I also added NOT NULL identifiers to the dex_trades table so we can catch/block if this ever happens again.

Fixes here:
https://github.com/duneanalytics/abstractions/pull/865/commits/4dd16e8dec44717c29dc9c4b911e3f3bdf9124da
https://github.com/duneanalytics/abstractions/pull/865/commits/abc414236bf5f714c7b3446ffbfe71776af03952

So I think moving forward we should delete and re-insert all OneInch dex.trades, then the prices runs should work fine!

**Comment by masquot** [comment]
Great job identifying and fixing the issue @MSilb7 :+1: 

Just deleting 1inch trades did not work. Had to `DROP` the full `dex.trades` table.

**Comment by MSilb7** [comment]
> Great job identifying and fixing the issue @MSilb7 👍
> 
> Just deleting 1inch trades did not work. Had to `DROP` the full `dex.trades` table.

Weird, does it seem to work now? It didn't seem like other DEXs were duplicating trades.

**Comment by masquot** [comment]
Updated all inserts + did backfill everywhere. Cron job set up. :rocket:

**Review by masquot — APPROVED** [review]

**Comment by MSilb7** [comment]
> Updated all inserts + did backfill everywhere. Cron job set up. 🚀

Wooo! This is awesome I'm pumped for this.

I found one small issue with how I handled for bridge token prices. Fixes here: https://github.com/duneanalytics/abstractions/pull/874

Otherwise, looks awesome so far!

**Pull request merged**
